// crabtag keytag firmware — phase 2a bring-up.
//
// Speaks the bridge's serial wire protocol (see transport/serial_link.py):
//   in :  "FRAME 8\n" then 8 lines of <= 20 chars  -> draw the prompt.
//         "IDLE\n"                                  -> return to the crab face.
//   out:  "BTN ALLOW" / "BTN DENY" / "BTN AUX" on a press, "READY" on boot.
//
// Two display states:
//   IDLE   - two eyes on an orange background, alternating between black squares
//            and a happy ">  <" squint. Firmware-drawn; shown on boot too.
//   PROMPT - the 20x8 text frame from render.py, drawn verbatim at text size 1.
//
// Display: ST7735 1.8" 128x160 over software SPI (Adafruit_GFX), used in
// landscape (160x128). Module pins map LED/SCK/SDA/A0/RST/CS.

#include <Adafruit_GFX.h>
#include <Adafruit_ST7735.h>
#include <Arduino.h>
#include <SPI.h>

#include "badapple_data.h"  // PROTOTYPE: generated by encode_embed.py, not hand-written

// The link is chosen at build time: KEYTAG_WIFI -> WiFi/WebSocket ("away"),
// otherwise BLE ("home"). The display, buttons, and line parser are shared.
#ifdef KEYTAG_WIFI
#include <WebSocketsClient.h>
#include <WiFi.h>
#include <WiFiMulti.h>

#include <cstring>

#include "secrets.h"  // WIFI_SSID_1/2, WIFI_PASS_1/2, KEYTAG_TOKEN, BRIDGE_HOST / BRIDGE_PORT
#else
#include <NimBLEDevice.h>
// Nordic UART Service: the line protocol over BLE. Bridge writes frames to RX,
// the keytag notifies button presses on TX. Same bytes as the serial link.
#define NUS_SERVICE "6e400001-b5a3-f393-e0a9-e50e24dcca9e"
#define NUS_RX "6e400002-b5a3-f393-e0a9-e50e24dcca9e"
#define NUS_TX "6e400003-b5a3-f393-e0a9-e50e24dcca9e"
#endif

// Pins come from build flags (see platformio.ini) so one source serves both boards.
// A0 on the module is DC; SDA is MOSI.
#ifndef PIN_TFT_CS
#define PIN_TFT_CS 7
#endif
#ifndef PIN_TFT_DC
#define PIN_TFT_DC 10
#endif
#ifndef PIN_TFT_RST
#define PIN_TFT_RST 3
#endif
#ifndef PIN_TFT_MOSI
#define PIN_TFT_MOSI 6
#endif
#ifndef PIN_TFT_SCLK
#define PIN_TFT_SCLK 4
#endif

// Buttons, active-low with internal pull-ups. Left = deny, right = allow,
// mirroring the on-screen "x deny ... allow v" affordance; middle = aux (reserved).
#ifndef BTN_DENY_PIN
#define BTN_DENY_PIN 0
#endif
#ifndef BTN_AUX_PIN
#define BTN_AUX_PIN 1
#endif
#ifndef BTN_ALLOW_PIN
#define BTN_ALLOW_PIN 21
#endif

// Onboard status LED (C3 SuperMini = GPIO8, active-low). Set to -1 to disable.
#ifndef LED_PIN
#define LED_PIN -1
#endif

// Hardware SPI constructor: (spiClass, cs, dc, rst). ESP32's GPIO matrix lets
// the SPI peripheral route to the *same* MOSI/SCLK pins already wired for
// software SPI -- see SPI.begin() in setup(). ST7735 is write-only (no miso).
// Was: Adafruit_ST7735(PIN_TFT_CS, PIN_TFT_DC, PIN_TFT_MOSI, PIN_TFT_SCLK, PIN_TFT_RST)
Adafruit_ST7735 tft(&SPI, PIN_TFT_CS, PIN_TFT_DC, PIN_TFT_RST);

constexpr uint8_t PIN_DENY = BTN_DENY_PIN;
constexpr uint8_t PIN_AUX = BTN_AUX_PIN;
constexpr uint8_t PIN_ALLOW = BTN_ALLOW_PIN;

// Landscape geometry (after setRotation(1)).
constexpr int SCREEN_W = 160;
constexpr int SCREEN_H = 128;

constexpr int COLS = 20;
constexpr int ROWS = 8;
constexpr int MARGIN_X = 6;
constexpr int MARGIN_Y = 4;
constexpr int LINE_H = 15;  // 8 rows * 15 = 120, fits the 128 px landscape height

uint16_t CRAB;      // Claude-crab coral (header bar + idle background)
uint16_t DENY_COL;  // red deny button
uint16_t ALLOW_COL; // green allow button
uint16_t DIM;       // muted grey for secondary text
// all set in setup() via color565

enum class Mode { IDLE, PROMPT, USAGE, REMINDER };
Mode mode = Mode::IDLE;

String frame[ROWS];

// usage meter (set by the bridge's USAGE command; not currently shown on any
// screen, kept for a future affordance -- the real plan bars below replaced it
// as the usage screen's headline content)
float usageCost = 0;
long usageTokens = 0;
int usagePct = 0;

// real plan-limit usage (set by the bridge's PLAN command, itself sourced from
// the actual `claude` /usage command). -1 = not yet known.
int planSessionPct = -1;
int planWeekPct = -1;

// ---- incoming serial: a tiny line-buffered state machine ----
String lineBuf;
int expectRows = 0;  // >0 while consuming a frame body
int rowIndex = 0;

// ================= idle moods =================
// The idle face is one of several moods the bridge sets to mirror Claude Code:
// sleepy when idle, focused mid-turn, wide-eyed + claws on a prompt, dizzy when
// rate-limited, party on a long clean finish.

constexpr int EYE_LX = 56, EYE_RX = 104, EYE_Y = 64;  // centred on the 160x128 screen
constexpr int EYE_HALF = 12;

enum class Mood { AWAKE, SLEEPY, FOCUS, DIZZY, SMOKE, COOK };
Mood mood = Mood::AWAKE;

bool blinking = false;
uint32_t blinkAt = 0, blinkUntil = 0, animAt = 0;
float dizzySpin = 0;
int smokePhase = 0;

// Wipe the whole face band to orange (moods draw beyond the eye boxes).
void wipeFace() { tft.fillRect(0, EYE_Y - 34, SCREEN_W, 74, CRAB); }

void eyeSquare(int cx) {
  tft.fillRect(cx - EYE_HALF, EYE_Y - EYE_HALF, 2 * EYE_HALF, 2 * EYE_HALF, ST77XX_BLACK);
}
void eyeSquint(int cx, bool right) {  // ">" / "<"
  const int e = 11;
  for (int t = 0; t < 4; t++) {
    int s = right ? -1 : 1;
    tft.drawLine(cx - s * e + t * s, EYE_Y - e, cx + s * e + t * s, EYE_Y, ST77XX_BLACK);
    tft.drawLine(cx + s * e + t * s, EYE_Y, cx - s * e + t * s, EYE_Y + e, ST77XX_BLACK);
  }
}
void eyeSleepy(int cx) {  // half-lidded: lower half + a droopy lid line
  tft.fillRect(cx - EYE_HALF, EYE_Y + 2, 2 * EYE_HALF, EYE_HALF - 2, ST77XX_BLACK);
  tft.fillRect(cx - EYE_HALF - 2, EYE_Y - 1, 2 * EYE_HALF + 4, 3, ST77XX_BLACK);
}
void eyeFlat(int cx) {  // fully shut (blink)
  tft.fillRect(cx - EYE_HALF - 2, EYE_Y - 1, 2 * EYE_HALF + 4, 3, ST77XX_BLACK);
}
void eyeFocus(int cx, bool right) {  // narrowed, angled inward-down = concentrating
  for (int t = 0; t < 5; t++) {
    if (!right) tft.drawLine(cx - EYE_HALF, EYE_Y - 4 + t, cx + EYE_HALF, EYE_Y + 4 + t, ST77XX_BLACK);
    else        tft.drawLine(cx - EYE_HALF, EYE_Y + 4 + t, cx + EYE_HALF, EYE_Y - 4 + t, ST77XX_BLACK);
  }
}
void eyeSpiral(int cx, float spin) {
  for (int i = 0; i < 42; i++) {
    float a = i * 0.55f + spin, r = i * 0.30f;
    tft.fillRect(cx + (int)(r * cosf(a)), EYE_Y + (int)(r * sinf(a)), 2, 2, ST77XX_BLACK);
  }
}
// ---- props drawn on the full orange face (no body, no black background) ----
void drawBarEyes(int hw, int hh) {  // two vertical eyes on the face
  tft.fillRect(EYE_LX - hw, EYE_Y - hh, 2 * hw, 2 * hh, ST77XX_BLACK);
  tft.fillRect(EYE_RX - hw, EYE_Y - hh, 2 * hw, 2 * hh, ST77XX_BLACK);
}
// Rising puffs, animated by `phase`. Drawn (and wiped) in a column by animateMood.
void drawSmoke(int x, int baseY, int phase) {
  const uint16_t sm = tft.color565(225, 225, 225);
  for (int i = 0; i < 4; i++) {
    int p = (phase + i * 8) % 32;
    tft.fillRect(x + (((p / 5) % 2) ? 3 : -1), baseY - p, 4, 4, sm);
  }
}
void drawCigarette() {  // in the mouth area (smoke is animated separately)
  const int cy = 100;
  tft.fillRect(74, cy, 38, 6, ST77XX_WHITE);              // stick
  tft.fillRect(74, cy, 9, 6, tft.color565(150, 95, 55));  // filter
  tft.fillRect(108, cy, 4, 6, ST77XX_RED);                // lit tip
}
void drawChefHat() {  // white hat across the top of the face
  tft.fillRoundRect(44, 2, 72, 22, 9, ST77XX_WHITE);  // puffy top
  tft.fillRect(52, 22, 56, 12, ST77XX_WHITE);         // band
  const uint16_t g = tft.color565(205, 205, 205);
  for (int i = 0; i < 4; i++) tft.drawFastVLine(62 + i * 12, 24, 8, g);
}
void drawPan() {  // frying pan across the bottom, food (steam is animated separately)
  const int px = 90, py = 104;
  const uint16_t dark = tft.color565(40, 40, 45);
  tft.fillRoundRect(px, py, 44, 16, 7, dark);
  tft.fillRect(px + 42, py + 5, 24, 5, dark);  // handle
  tft.fillRect(px + 9, py + 4, 4, 4, ST77XX_RED);
  tft.fillRect(px + 20, py + 5, 4, 4, ST77XX_GREEN);
  tft.fillRect(px + 31, py + 4, 4, 4, ST77XX_YELLOW);
}

void drawMoodBase() {
  switch (mood) {
    case Mood::AWAKE:  eyeSquare(EYE_LX); eyeSquare(EYE_RX); break;
    case Mood::SLEEPY: eyeSleepy(EYE_LX); eyeSleepy(EYE_RX); break;
    case Mood::FOCUS:  eyeFocus(EYE_LX, false); eyeFocus(EYE_RX, true); break;
    case Mood::DIZZY:  eyeSpiral(EYE_LX, dizzySpin); eyeSpiral(EYE_RX, -dizzySpin); break;
    case Mood::SMOKE:  drawBarEyes(4, 11); drawCigarette(); break;
    case Mood::COOK:   drawBarEyes(6, 15); drawChefHat(); drawPan(); break;
  }
}

void setMood(Mood m) {
  mood = m;
  blinking = false;
  dizzySpin = 0;
  tft.fillScreen(CRAB);
  drawMoodBase();
  blinkAt = millis() + 2200 + (uint32_t)random(0, 1800);
  animAt = millis();
}

void enterIdle() {
  mode = Mode::IDLE;
  setMood(mood);  // redraw the current mood as the idle face
}

void animateMood() {
  const uint32_t now = millis();
  switch (mood) {
    case Mood::AWAKE:
      if (!blinking && now >= blinkAt) {
        blinking = true; blinkUntil = now + 180;
        wipeFace(); eyeSquint(EYE_LX, false); eyeSquint(EYE_RX, true);
      } else if (blinking && now >= blinkUntil) {
        blinking = false; wipeFace(); eyeSquare(EYE_LX); eyeSquare(EYE_RX);
        blinkAt = now + 2200 + (uint32_t)random(0, 2600);
      }
      break;
    case Mood::SLEEPY:
      if (!blinking && now >= blinkAt) {
        blinking = true; blinkUntil = now + 260;
        wipeFace(); eyeFlat(EYE_LX); eyeFlat(EYE_RX);
      } else if (blinking && now >= blinkUntil) {
        blinking = false; wipeFace(); eyeSleepy(EYE_LX); eyeSleepy(EYE_RX);
        blinkAt = now + 3500 + (uint32_t)random(0, 3000);
      }
      break;
    case Mood::DIZZY:
      if (now - animAt > 110) {
        animAt = now; dizzySpin += 0.4f;
        wipeFace(); eyeSpiral(EYE_LX, dizzySpin); eyeSpiral(EYE_RX, -dizzySpin);
      }
      break;
    case Mood::SMOKE:
      if (now - animAt > 150) {
        animAt = now;
        smokePhase = (smokePhase + 3) % 32;
        tft.fillRect(110, 62, 16, 40, CRAB);  // wipe the smoke column
        drawSmoke(114, 96, smokePhase);
      }
      break;
    case Mood::COOK:
      if (now - animAt > 150) {
        animAt = now;
        smokePhase = (smokePhase + 3) % 32;
        tft.fillRect(110, 66, 16, 38, CRAB);  // wipe the steam column
        drawSmoke(114, 100, smokePhase);
      }
      break;
    default:
      break;  // FOCUS and ALERT are static
  }
}

Mood parseMood(const String& s) {
  if (s == "SLEEPY") return Mood::SLEEPY;
  if (s == "FOCUS") return Mood::FOCUS;
  if (s == "DIZZY") return Mood::DIZZY;
  if (s == "SMOKE") return Mood::SMOKE;
  if (s == "COOK") return Mood::COOK;
  return Mood::AWAKE;
}

// Local preview: step through the moods (bound to the middle button).
void cycleMood() {
  int n = (int)mood + 1;
  if (n > (int)Mood::COOK) n = 0;
  setMood((Mood)n);
}

// ================= prompt frame =================

// render.py's fixed row layout (see render.py): 0 header, 1 divider,
// 2-4 payload, 5 context, 6 divider, 7 affordance. The firmware styles it:
// the divider/affordance rows become graphical chrome, the rest is drawn verbatim.
void drawButton(int x, int y, int w, int h, uint16_t bg, const char* label) {
  tft.fillRoundRect(x, y, w, h, 4, bg);
  const int tx = x + (w - (int)strlen(label) * 6) / 2;
  const int ty = y + (h - 8) / 2;
  tft.setTextSize(1);
  tft.setTextColor(ST77XX_WHITE);
  tft.setCursor(tx, ty);
  tft.print(label);
}

void drawFrame() {
  mode = Mode::PROMPT;
  tft.fillScreen(ST77XX_BLACK);
  tft.setTextSize(1);

  // header bar: tool name + queue depth (row 0), dark text on coral
  tft.fillRect(0, 0, SCREEN_W, 16, CRAB);
  tft.setTextColor(ST77XX_BLACK);
  tft.setCursor(5, 4);
  tft.print(frame[0]);

  // little coral claws flanking the header — claws-up on a prompt
  for (int s = 0; s < 2; s++) {
    int x = s == 0 ? 3 : SCREEN_W - 9;
    tft.drawLine(x, 16, x + 2, 25, CRAB);
    tft.drawLine(x + 6, 16, x + 4, 25, CRAB);
  }

  // command payload (rows 2-4), white
  tft.setTextColor(ST77XX_WHITE);
  int y = 28;
  for (int r = 2; r <= 4; r++) {
    tft.setCursor(6, y);
    tft.print(frame[r]);
    y += 13;
  }

  // context (row 5), muted
  tft.setTextColor(DIM);
  tft.setCursor(6, 74);
  tft.print(frame[5]);

  // deny / allow buttons mirroring the physical left / right buttons
  drawButton(6, 104, 68, 20, DENY_COL, "DENY");
  drawButton(SCREEN_W - 6 - 68, 104, 68, 20, ALLOW_COL, "ALLOW");
}

// ================= usage screen (left button when idle) =================
// Shows the real plan-limit bars from the bridge's PLAN command -- the actual
// `claude` /usage session and week percentages, not an estimate.

void drawPlanBar(int y, const char* label, int pct) {
  tft.setTextSize(1);
  tft.setTextColor(DIM);
  tft.setCursor(6, y);
  tft.print(label);

  tft.setTextColor(ST77XX_WHITE);
  tft.setCursor(SCREEN_W - 30, y);
  if (pct < 0) {
    tft.print("--");
  } else {
    tft.print(pct);
    tft.print("%");
  }

  const int bx = 6, by = y + 12, bw = SCREEN_W - 12, bh = 14;
  tft.drawRect(bx, by, bw, bh, ST77XX_WHITE);
  if (pct >= 0) {
    int clamped = pct > 100 ? 100 : pct;
    int fill = (bw - 2) * clamped / 100;
    uint16_t c = clamped >= 90 ? ST77XX_RED : (clamped >= 70 ? ST77XX_YELLOW : ST77XX_GREEN);
    if (fill > 0) tft.fillRect(bx + 1, by + 1, fill, bh - 2, c);
  }
}

void drawUsage() {
  mode = Mode::USAGE;
  tft.fillScreen(ST77XX_BLACK);
  tft.setTextSize(1);
  tft.setTextColor(CRAB);
  tft.setCursor(6, 4);
  tft.print("PLAN USAGE");

  drawPlanBar(20, "SESSION", planSessionPct);
  drawPlanBar(64, "WEEK", planWeekPct);

  tft.setTextSize(1);
  tft.setTextColor(DIM);
  tft.setCursor(6, 112);
  tft.print(planSessionPct < 0 ? "waiting for data" : "any button: back");
}

// ================= reminders (bridge-scheduled nudges) =================
// The bridge decides *when* -- real wall-clock time, no clock or schedule on
// the device -- this only knows how to draw the four fixed kinds it's told.
// Same full-screen-coral, black-prop composition as the SMOKE/COOK moods
// (fillScreen(CRAB) + eyes + a held prop), not a separate icon style.

constexpr uint32_t REMINDER_DISPLAY_MS = 15000;
uint32_t reminderUntil = 0;

void drawDumbbell(int cx, int cy) {
  tft.fillRect(cx - 7, cy - 2, 14, 4, ST77XX_BLACK);           // bar
  tft.fillRoundRect(cx - 14, cy - 7, 7, 14, 2, ST77XX_BLACK);  // left plate
  tft.fillRoundRect(cx + 7, cy - 7, 7, 14, 2, ST77XX_BLACK);   // right plate
}

void drawGymProp() {
  tft.fillRect(30, 40, 100, 6, ST77XX_WHITE);  // headband
  drawDumbbell(26, 62);                        // raised beside the head, both sides
  drawDumbbell(134, 62);
}

void drawCodeProp() {
  const int x = 118, y = 76;
  tft.drawRect(x, y, 30, 20, ST77XX_BLACK);          // laptop screen
  tft.fillRect(x - 4, y + 20, 38, 4, ST77XX_BLACK);  // base
  tft.setTextSize(1);
  tft.setTextColor(ST77XX_BLACK);
  tft.setCursor(x + 4, y + 6);
  tft.print("</>");
}

void drawWaterProp() {
  const uint16_t bottleLight = tft.color565(190, 215, 235);
  const uint16_t bottleBlue = tft.color565(70, 150, 220);
  const int x = 126, topY = 70;
  tft.fillRoundRect(x, topY, 18, 30, 4, bottleLight);  // body
  tft.fillRect(x + 5, topY - 8, 8, 9, bottleBlue);     // cap/neck
  tft.fillRect(x, topY + 12, 18, 7, bottleBlue);       // label band
}

void drawSupplementProp() {
  const int x = 122, y = 82;
  tft.fillRoundRect(x, y, 26, 13, 6, ST77XX_BLACK);
  tft.fillRoundRect(x, y, 13, 13, 6, DENY_COL);  // two-tone capsule
}

// mode/reminderUntil are set here; the caller (handleLine) has already
// checked the kind is one of the four known ones and that showing it now
// (idle, nothing else on screen) makes sense.
void drawReminder(const String& kind) {
  mode = Mode::REMINDER;
  tft.fillScreen(CRAB);
  eyeSquare(EYE_LX);
  eyeSquare(EYE_RX);

  if (kind == "GYM") {
    drawGymProp();
  } else if (kind == "CODE") {
    drawCodeProp();
  } else if (kind == "WATER") {
    drawWaterProp();
  } else {  // SUPPLEMENT
    drawSupplementProp();
  }

  reminderUntil = millis() + REMINDER_DISPLAY_MS;
}

// ================= serial in =================

void handleLine(const String& line) {
  if (expectRows > 0) {
    if (rowIndex < ROWS) frame[rowIndex] = line;
    rowIndex++;
    if (rowIndex >= expectRows) {
      expectRows = 0;
      drawFrame();
    }
    return;
  }
  if (line.startsWith("FRAME ")) {
    int n = line.substring(6).toInt();
    if (n < 1) n = 1;
    if (n > ROWS) n = ROWS;
    expectRows = n;
    rowIndex = 0;
  } else if (line == "IDLE") {
    enterIdle();
  } else if (line.startsWith("MOOD ")) {
    Mood m = parseMood(line.substring(5));
    mood = m;                        // remember it even during a prompt
    if (mode == Mode::IDLE) setMood(m);
  } else if (line.startsWith("USAGE ")) {
    int s1 = line.indexOf(' ', 6);
    int s2 = line.indexOf(' ', s1 + 1);
    if (s1 > 0 && s2 > 0) {
      usageCost = line.substring(6, s1).toFloat();
      usageTokens = line.substring(s1 + 1, s2).toInt();
      usagePct = line.substring(s2 + 1).toInt();
      if (mode == Mode::USAGE) drawUsage();  // live-refresh if being viewed
    }
  } else if (line.startsWith("PLAN ")) {
    int s1 = line.indexOf(' ', 5);
    if (s1 > 0) {
      planSessionPct = line.substring(5, s1).toInt();
      planWeekPct = line.substring(s1 + 1).toInt();
      if (mode == Mode::USAGE) drawUsage();  // live-refresh if being viewed
    }
  } else if (line.startsWith("REMIND ")) {
    String kind = line.substring(7);
    kind.trim();
    bool known = kind == "GYM" || kind == "CODE" || kind == "WATER" || kind == "SUPPLEMENT";
    // Only from idle: a reminder must never cover a live prompt or the usage
    // screen. Unknown kinds are dropped -- there's no sensible fallback the
    // way MOOD falls back to AWAKE.
    if (known && mode == Mode::IDLE) drawReminder(kind);
  }
}

// One byte of the FRAME/IDLE stream, from either serial or BLE, into the line
// buffer. Newline-framed, so it does not matter how BLE chunks the writes.
void feedByte(char c) {
  if (c == '\n') {
    handleLine(lineBuf);
    lineBuf = "";
  } else if (c != '\r') {
    lineBuf += c;
  }
}

void pollSerial() {
  while (Serial.available()) feedByte((char)Serial.read());
}

// ================= link: WiFi/WebSocket ("away") or BLE ("home") =================
// Each variant provides setupLink(), loopLink(), and sendLineLink(line).

#ifdef KEYTAG_WIFI

WebSocketsClient webSocket;
WiFiMulti wifiMulti;
bool wsConnected = false;

void onWsEvent(WStype_t type, uint8_t* payload, size_t length) {
  if (type == WStype_CONNECTED) {
    wsConnected = true;
    Serial.println("[ws] connected to bridge");
  } else if (type == WStype_DISCONNECTED) {
    wsConnected = false;
    Serial.println("[ws] disconnected");
  } else if (type == WStype_TEXT) {
    for (size_t i = 0; i < length; i++) feedByte((char)payload[i]);
  }
}

void setupLink() {
  WiFi.mode(WIFI_STA);
  // Two candidate networks (e.g. home WiFi + a phone hotspot for "away" use).
  // WiFiMulti tries each and keeps whichever is actually in range; leave
  // WIFI_SSID_2 empty in secrets.h to register only one.
  wifiMulti.addAP(WIFI_SSID_1, WIFI_PASS_1);
  if (strlen(WIFI_SSID_2) > 0) wifiMulti.addAP(WIFI_SSID_2, WIFI_PASS_2);
  Serial.println("[wifi] joining (multi-AP)");
  String path = String("/keytag?token=") + KEYTAG_TOKEN;
#if defined(BRIDGE_TLS) && BRIDGE_TLS
#ifdef BRIDGE_HAS_CA
  webSocket.beginSslWithCA(BRIDGE_HOST, BRIDGE_PORT, path.c_str(), BRIDGE_CA_CERT);  // validated wss
#else
  webSocket.beginSSL(BRIDGE_HOST, BRIDGE_PORT, path.c_str());  // wss, cert NOT validated (set BRIDGE_CA_CERT)
#endif
#else
  webSocket.begin(BRIDGE_HOST, BRIDGE_PORT, path.c_str());  // plain ws:// (LAN)
#endif
  webSocket.onEvent(onWsEvent);
  webSocket.setReconnectInterval(3000);
}

void loopLink() {
  // wifiMulti.run() is what actually (re)connects -- it picks whichever
  // registered AP is in range, so it must run again after a drop, not just
  // once on boot. It can block for its timeout while actively attempting a
  // connection, so it's throttled and only called while not already up;
  // once connected this is just a status check every loop() iteration.
  static bool wifiUp = false;
  static uint32_t lastAttempt = 0;
  wl_status_t st = WiFi.status();
  if (!wifiUp && st == WL_CONNECTED) {
    wifiUp = true;
    Serial.print("[wifi] connected to ");
    Serial.print(WiFi.SSID());
    Serial.print(", IP ");
    Serial.println(WiFi.localIP());
    configTime(0, 0, "pool.ntp.org", "time.google.com");  // real time for TLS cert validity
  } else if (wifiUp && st != WL_CONNECTED) {
    wifiUp = false;  // dropped -- fall through to reconnect attempts below
    Serial.println("[wifi] lost connection, reconnecting");
  } else if (!wifiUp && millis() - lastAttempt > 3000) {
    lastAttempt = millis();
    Serial.print("[wifi] attempting (status ");
    Serial.print((int)st);
    Serial.println(")");
    wifiMulti.run(3000);  // bounded attempt against the strongest known AP
  }
  webSocket.loop();
}

void sendLineLink(const String& line) {
  if (wsConnected) {
    String payload = line;  // sendTXT wants a non-const String&
    webSocket.sendTXT(payload);
  }
}

#else  // BLE (Nordic UART Service)

NimBLECharacteristic* txChar = nullptr;
bool bleConnected = false;

class RxCallbacks : public NimBLECharacteristicCallbacks {
  void onWrite(NimBLECharacteristic* c) override {
    std::string v = c->getValue();
    for (char ch : v) feedByte(ch);
  }
};

class ServerCallbacks : public NimBLEServerCallbacks {
  void onConnect(NimBLEServer*) override { bleConnected = true; }
  void onDisconnect(NimBLEServer*) override {
    bleConnected = false;
    NimBLEDevice::startAdvertising();  // stay discoverable
  }
};

void setupLink() {
  NimBLEDevice::init("crabtag");
  NimBLEServer* server = NimBLEDevice::createServer();
  server->setCallbacks(new ServerCallbacks());

  NimBLEService* svc = server->createService(NUS_SERVICE);
  NimBLECharacteristic* rx =
      svc->createCharacteristic(NUS_RX, NIMBLE_PROPERTY::WRITE | NIMBLE_PROPERTY::WRITE_NR);
  rx->setCallbacks(new RxCallbacks());
  txChar = svc->createCharacteristic(NUS_TX, NIMBLE_PROPERTY::NOTIFY);
  svc->start();

  NimBLEAdvertising* adv = NimBLEDevice::getAdvertising();
  adv->addServiceUUID(NUS_SERVICE);
  adv->setScanResponse(true);
  NimBLEDevice::startAdvertising();
}

void loopLink() {}

void sendLineLink(const String& line) {
  if (txChar != nullptr && bleConnected) {
    txChar->setValue((uint8_t*)line.c_str(), line.length());
    txChar->notify();
  }
}

#endif

// ================= buttons =================
// DENY and ALLOW are always the prompt decision, immediately on press, in
// every mode except the two carve-outs below -- never a wait-and-see hold in
// the one place responsiveness actually matters (a live prompt).
//   - AUX, while idle: tap cycles moods (unchanged); a long press shows the
//     usage screen -- the one button gets a second, related job instead of
//     handing usage-viewing to DENY/ALLOW and diluting their single purpose.
//   - DENY, while viewing the usage screen: a long press asks the bridge to
//     resync (fresh plan-limit data) rather than dismissing; an ordinary tap
//     still dismisses, same as any other button would.
// Scheduled reminders and the transports' automatic reconnect watchers don't
// depend on a button at all, so neither RESYNC nor usage-viewing is load-
// bearing for anything else to keep working.

constexpr uint32_t LONG_PRESS_MS = 700;

struct Button {
  uint8_t pin;
  const char* name;
  bool wasPressed;
  uint32_t lastEdge;
  uint32_t pressedAt;
  bool longFired;
};

Button buttons[] = {
    {PIN_DENY, "DENY", false, 0, 0, false},
    {PIN_ALLOW, "ALLOW", false, 0, 0, false},
    {PIN_AUX, "AUX", false, 0, 0, false},
};

void sendLine(const String& line) {
  Serial.println(line);       // serial path (and handy debug)
  sendLineLink(line + "\n");  // BLE notify or WebSocket send, per build
}

void sendButton(const char* name) {
  sendLine(String("BTN ") + name);
}

void sendResync() {
  sendLine("RESYNC");
}

void playBadApple();  // defined below; pollButtons() triggers it on an ALLOW hold

void pollButtons() {
  uint32_t now = millis();
  for (Button& b : buttons) {
    bool pressed = digitalRead(b.pin) == LOW;
    bool holdCapable = (mode == Mode::IDLE && (b.pin == PIN_AUX || b.pin == PIN_ALLOW)) ||
                        (mode == Mode::USAGE && b.pin == PIN_DENY);

    if (pressed && !b.wasPressed && (now - b.lastEdge) > 40) {
      b.lastEdge = now;
      b.pressedAt = now;
      b.longFired = false;
      if (!holdCapable) {
        if (mode == Mode::USAGE || mode == Mode::REMINDER) {
          enterIdle();  // any other button leaves the usage/reminder screen
        } else {
          sendButton(b.name);  // prompt decisions and everything else
        }
      }
    } else if (pressed && b.wasPressed && holdCapable && !b.longFired
               && (now - b.pressedAt) >= LONG_PRESS_MS) {
      b.longFired = true;
      if (mode == Mode::IDLE && b.pin == PIN_AUX) {
        drawUsage();  // AUX held while idle: show the usage screen
      } else if (mode == Mode::IDLE && b.pin == PIN_ALLOW) {
        playBadApple();  // ALLOW held while idle: play the demo clip (blocks ~9s)
      } else {
        sendResync();  // DENY held while viewing usage: refresh it
      }
    } else if (!pressed && b.wasPressed && holdCapable && !b.longFired) {
      if (mode == Mode::IDLE && b.pin == PIN_AUX) {
        cycleMood();  // AUX released before the hold threshold: ordinary tap
      } else if (mode == Mode::IDLE && b.pin == PIN_ALLOW) {
        sendButton(b.name);  // ALLOW released before the hold threshold: ordinary tap, no idle meaning
      } else {
        enterIdle();  // DENY released before the hold threshold (in USAGE): dismiss, like any button
      }
    }
    b.wasPressed = pressed;
  }
}

// Onboard LED = link status: solid when fully online, slow blink when the WiFi
// is up but not yet talking to the bridge, fast blink when disconnected.
void updateLed() {
#if LED_PIN >= 0
  static uint32_t last = 0;
  static bool on = false;
#ifdef KEYTAG_WIFI
  bool wifiUp = (WiFi.status() == WL_CONNECTED);
  uint32_t interval = (wifiUp && wsConnected) ? 0 : (wifiUp ? 700 : 150);
#else
  uint32_t interval = bleConnected ? 0 : 150;
#endif
  uint32_t now = millis();
  if (interval == 0) {
    on = true;
  } else if (now - last >= interval) {
    last = now;
    on = !on;
  }
  digitalWrite(LED_PIN, on ? LOW : HIGH);  // active low: LOW = lit
#endif
}

// ================= Bad Apple prototype (long-press ALLOW while idle) =======
// Confirmed ~1fps realistic ceiling on this software-SPI link -- the encoder
// (encode_embed.py) samples source video at 1fps to match, so playback runs
// at roughly its real-world pace rather than in slow motion. Each frame is
// either a keyframe (direct RLE) or a delta (RLE of XOR against the previous
// *decoded* frame, whichever the encoder found smaller) -- decoded into a
// buffer first, then converted to horizontal-line draws, so row-spanning RLE
// runs don't have to be split during decode.
//
// playBadApple() blocks for the full playback (~1s/frame, delay()-based) --
// no button/link/LED polling happens while it plays. Acceptable for a novelty
// feature triggered deliberately; not something any other feature depends on.

constexpr int BADAPPLE_ROW_BYTES = (BADAPPLE_WIDTH + 7) / 8;
constexpr int BADAPPLE_FRAME_BYTES = BADAPPLE_ROW_BYTES * BADAPPLE_HEIGHT;

uint8_t badappleBuf[BADAPPLE_FRAME_BYTES];      // current frame, true pixel values
uint8_t badappleScratch[BADAPPLE_FRAME_BYTES];  // this frame's payload, freshly unpacked

uint32_t decodeVarint(const uint8_t* data, uint32_t& pos) {
  uint32_t result = 0;
  int shift = 0;
  while (true) {
    uint8_t b = data[pos++];
    result |= (uint32_t)(b & 0x7F) << shift;
    if (!(b & 0x80)) break;
    shift += 7;
  }
  return result;
}

// Unpacks the RLE-encoded bit-run-lengths in data[0..len) into `out`, packed
// MSB-first per byte, overwriting exactly BADAPPLE_FRAME_BYTES bytes.
void rleUnpackToBuffer(const uint8_t* data, uint32_t len, uint8_t* out) {
  memset(out, 0, BADAPPLE_FRAME_BYTES);
  uint32_t pos = 0;
  uint8_t curBit = data[pos++];
  uint32_t bitIndex = 0;
  while (pos < len) {
    uint32_t run = decodeVarint(data, pos);
    if (curBit) {
      for (uint32_t i = 0; i < run; i++) {
        uint32_t idx = bitIndex + i;
        out[idx / 8] |= (0x80 >> (idx % 8));
      }
    }
    bitIndex += run;
    curBit ^= 1;
  }
}

// One SPI transaction + CS assertion for the whole frame (writeFastHLine,
// unlike drawFastHLine, doesn't self-wrap one per call) -- a busy frame can
// be a few hundred short runs, and paying the per-call setup cost that many
// times was the actual bottleneck, not raw SPI bandwidth.
// writeFastHLine still re-issues a CASET/RASET/RAMWR address-window command
// sequence per run (hundreds per frame on busy content) -- since RLE runs are
// already in raster-scan order matching the display's own auto-increment,
// setting the address window ONCE for the whole frame and streaming every run
// as writeColor() (no re-addressing) skips all of that repeated overhead.
void drawBadAppleFrame(const uint8_t* buf) {
  tft.startWrite();
  tft.setAddrWindow(0, 0, BADAPPLE_WIDTH, BADAPPLE_HEIGHT);
  for (int y = 0; y < BADAPPLE_HEIGHT; y++) {
    int x = 0;
    while (x < BADAPPLE_WIDTH) {
      int bit = (buf[y * BADAPPLE_ROW_BYTES + x / 8] >> (7 - (x % 8))) & 1;
      int runStart = x;
      x++;
      while (x < BADAPPLE_WIDTH) {
        int b = (buf[y * BADAPPLE_ROW_BYTES + x / 8] >> (7 - (x % 8))) & 1;
        if (b != bit) break;
        x++;
      }
      tft.writeColor(bit ? ST77XX_BLACK : ST77XX_WHITE, x - runStart);
    }
  }
  tft.endWrite();
}

bool anyButtonPressed() {
  return digitalRead(PIN_DENY) == LOW || digitalRead(PIN_ALLOW) == LOW || digitalRead(PIN_AUX) == LOW;
}

void playBadApple() {
  // The long-press that triggered this is likely still physically held --
  // check for a *new* press only after it's released, or playback would stop
  // itself on frame 0 every time.
  while (digitalRead(PIN_ALLOW) == LOW) yield();

  uint32_t offset = 0;
  uint32_t playStart = millis();
  int framesPlayed = 0;
  for (int i = 0; i < BADAPPLE_FRAME_COUNT; i++) {
    if (anyButtonPressed()) {
      Serial.println("[badapple] stopped early by button press");
      break;
    }
    uint32_t frameStart = millis();
    const BadAppleFrameMeta& meta = BADAPPLE_INDEX[i];
    rleUnpackToBuffer(BADAPPLE_DATA + offset, meta.length, badappleScratch);
    if (meta.tag == 1) {  // delta: XOR against the previous true frame
      for (int b = 0; b < BADAPPLE_FRAME_BYTES; b++) badappleScratch[b] ^= badappleBuf[b];
    }
    memcpy(badappleBuf, badappleScratch, BADAPPLE_FRAME_BYTES);
    drawBadAppleFrame(badappleBuf);
    uint32_t workMs = millis() - frameStart;
    // Hardware SPI decodes+draws well under the encoded frame interval now --
    // pad back up to it so playback matches the source's actual tempo instead
    // of just running as fast as the display allows.
    if (workMs < BADAPPLE_FRAME_INTERVAL_MS) delay(BADAPPLE_FRAME_INTERVAL_MS - workMs);
    Serial.printf("[badapple] frame %d work: %lums (padded to %lums)\n", i, workMs,
                  millis() - frameStart);
    offset += meta.length;
    framesPlayed++;
    loopLink();  // keep the WiFi/WS link (or BLE stack) serviced during long playback
    yield();     // give the RTOS scheduler a turn -- minutes of no yield risks a watchdog reset
  }
  Serial.printf("[badapple] %d/%d frames played: %lums\n", framesPlayed, BADAPPLE_FRAME_COUNT,
                millis() - playStart);
  enterIdle();  // clean handoff back to the normal face, not left on the last frame
}

void setup() {
  Serial.begin(115200);
  pinMode(PIN_DENY, INPUT_PULLUP);
  pinMode(PIN_AUX, INPUT_PULLUP);
  pinMode(PIN_ALLOW, INPUT_PULLUP);
#if LED_PIN >= 0
  pinMode(LED_PIN, OUTPUT);
  digitalWrite(LED_PIN, HIGH);  // off (active low)
#endif

  randomSeed(micros());

  // Route the hardware SPI peripheral to the existing wiring via the GPIO
  // matrix (no rewiring): sck, miso(-1, unused), mosi, ss.
  SPI.begin(PIN_TFT_SCLK, -1, PIN_TFT_MOSI, PIN_TFT_CS);
  tft.setSPISpeed(8000000);  // conservative to start -- this is breadboard wiring,
                              // never tested past bit-banged speeds; raise if stable

  tft.initR(INITR_BLACKTAB);  // 1.8" 128x160; if colors/edges look off, try INITR_GREENTAB
  tft.setRotation(1);         // landscape 160x128 (try 3 to flip 180°)
  CRAB = tft.color565(205, 92, 70);  // Claude coral (green pulled down; ST7735 renders green hot)
  DENY_COL = tft.color565(198, 58, 52);
  ALLOW_COL = tft.color565(58, 158, 92);
  DIM = tft.color565(150, 150, 150);

  setupLink();
  enterIdle();
  Serial.println("READY");
}

void loop() {
  loopLink();
  updateLed();
  pollSerial();
  pollButtons();
  if (mode == Mode::IDLE) {
    animateMood();
  } else if (mode == Mode::REMINDER && millis() >= reminderUntil) {
    enterIdle();  // auto-dismiss; a button press also does this early
  }
}
